version: '3'

services:

  test_database:
    container_name: ha_pg_database
    image: postgres
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_DB=postgress
      - POSTGRES_PASSWORD=postgress
      - TZ=GMT+3
      - POSTGRES_EXTENSIONS=pg_trgm
    ports:
      - 5432:5432
  redis:
    image: 'redis:alpine'
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    ports:
      - "6379:6379"
  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    depends_on:
      - redis-server
    volumes:
      - ./redis-sentinel/redis-ui:/settings
