version: '3'

services:

  test_database:
    container_name: ha_pg_database
    image: postgres
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_DB=postgress
      - POSTGRES_PASSWORD=postgress
      - TZ=GMT+3
      - POSTGRES_EXTENSIONS=pg_trgm
    ports:
      - 5432:5432
