export enum MemeModerationMenusEnum {
  MODERATION = 'MODERATION',
  APPROVAL = 'APPROVAL',
  REJECT = 'REJECT',
  PUBLICATION = 'PUBLICATION',
  BAN = 'BAN',
  STRIKE = 'STRIKE',
  OBSERVATORY_POST = 'OBSERVATORY_POST',
}
