export enum ObservatoryPostMenusEnum {
  POST_MENU = 'observer_post_menu',
  DELETE_OBSERVER_POST = 'OBS_DELETE_POST',
  OBSERVATORY_PUBLICATION = 'OBSERVATORY_PUBLICATION',
  USER_MODERATE_POST = 'USER_MODERATE_POST',
}
