export enum AdminMenusEnum {
  ADMIN_START_MENU = 'ADMIN_START_MENU',
  TROLL_SETTINGS_MENU = 'TROLL_SETTINGS_MENU',
  TROLL_CHATS_MENU = 'TROLL_CHATS_MENU',
}

export enum ModeratorMenusEnum {
  MODERATOR_START_MENU = 'MODERATOR_START_MENU',
}

export enum UserMenusEnum {
  USER_START_MENU = 'USER_START_MENU',
}
