export enum PostModerationMenusEnum {
  MODERATION = 'MODERATION',
  APPROVAL = 'APPROVAL',
  REJECT = 'REJECT',
  PUBLICATION = 'PUBLICATION',
  BAN = 'BAN',
  STRIKE = 'STRIKE',
  DUPLICATE_CHECK = 'DUPLICATE_CHECK'
}
