export enum PublicationModesEnum {
  NOW_SILENT = 'NOW_SILENT',
  NEXT_INTERVAL = 'NEXT_INTERVAL',
  NIGHT_CRINGE = 'NIGHT_CRINGE',
  NEXT_MORNING = 'NEXT_MORNING',
  NEXT_MIDDAY = 'NEXT_MIDDAY',
  NEXT_EVENING = 'NEXT_EVENING',
  NEXT_NIGHT = 'NEXT_NIGHT',
}
