export enum ConversationsEnum {
  SEND_MEME_CONVERSATION = 'SEND_MEME_CONVERSATION',
  ADD_MODERATOR_CONVERSATION = 'ADD_MODERATOR_CONVERSATION',
  USER_ADMIN_CONVERSATION = 'USER_ADMIN_CONVERSATION',
  ADMIN_USER_CONVERSATION = 'ADMIN_USER_CONVERSATION',
}
