export enum PublicationModesEnum {
  NOW_SILENT = 'NOW_SILENT',
  NIGHT_CRINGE = 'NIGHT_CRINGE',
  NOW_WITH_ALARM = 'NOW_WITH_ALARM',
  NEXT_MORNING = 'NEXT_MORNING',
  NEXT_MIDDAY = 'NEXT_MIDDAY',
  NEXT_EVENING = 'NEXT_EVENING',
  NEXT_NIGHT = 'NEXT_NIGHT'
}
